# In this makefile we are accepting the input from user as a command line
# which gets stored in macro "file" and "mode"
build:
	gcc file_access.c -o myexe

run:
	./myexe ${file} ${mode}

clean:
	rm myexe

