# file macro created to input from command line interface
build:
	gcc print_file_names.c -o myexe

run:
	./myexe ${dir}

clean:
	rm myexe

help:
	@echo 'run program using command 'make dir='directory_name' run

